
name: diabetes_ml_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib
  - seaborn
  - mlflow=2.10.1
  - requests
  - pyyaml
